// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-73PGcrYCYrOvg5nWY4KBm1S4a8TXsQ',
    appId: '1:560020423608:web:231221ecdd10ab5849454d',
    messagingSenderId: '560020423608',
    projectId: 'safety-syncc',
    authDomain: 'safety-syncc.firebaseapp.com',
    storageBucket: 'safety-syncc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGd4BE6FhLKjskLAa2wMJTcKEly9Kxx48',
    appId: '1:560020423608:android:3e29a45a1d7a2e7449454d',
    messagingSenderId: '560020423608',
    projectId: 'safety-syncc',
    storageBucket: 'safety-syncc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1E_hUN46_xy9yrMeLSVJe04lMkrN7-KM',
    appId: '1:560020423608:ios:72a75072b60a007549454d',
    messagingSenderId: '560020423608',
    projectId: 'safety-syncc',
    storageBucket: 'safety-syncc.appspot.com',
    iosBundleId: 'com.example.safetySyncc',
  );
}
